name: dart_rest
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.0.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  mongo_dart: ^0.7.4+1
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.10
  http: ^0.13.0
  json_serializable: ^6.1.6
  meta: ^1.7.0
  mocktail: ^0.3.0
  test: ^1.15.0
  test_process: ^2.0.0
  very_good_analysis: ^2.4.0
